import pandas as pd
dataframe = pd.read_excel('sample454.xlsx')
print(dataframe)
print("============")
print("Number of rows and columns :" , dataframe.shape)	
print("====================================")
print("Emails:")
print(dataframe['Email'])
print("====================================")
print("Sort the data based on FirstName in ascending order:")
print(dataframe.sort_values('FirstName'))